### ISSUE TITLE
[Feature Request] Scroll-Bar in Side Navigation Bar is not matching Soft UI

### ISSUE THREAD

**Issue by nexadomain** [creativetimofficial/soft-ui-dashboard#14]
### What is your enhancement?
Default Scrollbar in Side Navigation Bar is not matching with the look of Theme. 
It would be great, if scroll bar is little thinner, with no button(arrow at the end) and thumb color matching with colour combination of Soft UI Theme.

My Solution:
-webkit-scrollbar {  width: 5px; } // For Decreasing Width of Default Scrollbar 

Rares and his team already developed great, Soft UI Dashboard. I don't want their great effort ruined by default Scrollbar. 
And, eagerly waiting for Pro Version.

**Comment by groovemen** [comment]
Hello @nexadomain, 

Thank you for using our products, and for your constructive feedback. We have fixed this issue by integrating perfectScrollbar plugin in the latest product update. 

All the best, 
Stefan
