### ISSUE TITLE
MVC.NET?

### ISSUE THREAD

**Issue by alanherron** [creativetimofficial/soft-ui-dashboard#16]
I recently purchased your soft-ui dasboard but wanted to inquire if there was an mvc.net version of the software or perhaps request assistance on setting it up in a MVC.net environment.

Thanks in advance!,
Alan

**Comment by nexadomain** [comment]
@alanherron Soft UI Dashboard is free product from Creative Tim. Still wondering, from  where purchased this!
Soft UI Dashboard Pro will be the paid product. But, it is still in development phase, and yet to launch, I guess!

If your MVC.net project uses HTML template(View Engine), then you can integrate it by own easily.
