### ISSUE TITLE
Proper way to handle a dashboard without a sidebar?

### ISSUE THREAD

**Issue by JoLoZ** [creativetimofficial/soft-ui-dashboard#36]
Hey there,
some parts of the dashboard that I'm building don't have a sidebar. However, when simply leaving the HTML code for the sidebar out, I'm encountering several JS bugs, which I have listed below.

### Firefox
- `TypeError: sidenav is null`
- `TypeError: referenceButtons is null`

### Chrome
- `TypeError: Cannot read properties of null (reading 'classList')`

So, what is the proper way to use the design system without a sidebar?

You can check my site for testing [here](https://3001-dashboard-4.pages.dev/).

**Comment by JoLoZ** [comment]
About the form, I'm sorry, but this is neither a Feature Request nor a Bug, just a question for clarification.

**Comment by groovemen** [comment]
Hello @JoLoZ,

Thank you for using our products, for those pages that you want to create without the sidebar, you can start from this page structure: https://demos.creative-tim.com/soft-ui-dashboard/pages/sign-in.html for example.
Or to fix the issue, you can change the imported script with un-minified one:
`<script src="../assets/js/soft-ui-dashboard.js?v=1.0.5"></script>`

Hope this information helps you.

All the best,
Stefan
