### ISSUE TITLE
[Bug] Modal/Sweets alerts does not block left panel

### ISSUE THREAD

**Issue by ShoghiMartinez** [creativetimofficial/soft-ui-dashboard#39]
### Version
Soft UI Dashboard Bootstrap
### Reproduction link
https://demos.creative-tim.com/soft-ui-dashboard-pro/pages/pages/sweet-alerts.html
### Operating System
Windows 10
### Device
Dell Laptop
### Browser & Version
Firefox 91.11.0esr (64-bit)
### Steps to reproduce
Create a modal
### What is expected?
Open a modal or sweet alert, any option or link outside modal must be blocked 
### What is actually happening?
Left panel links, page and options keeps working, options get highligthed. 

---

**Comment by ShoghiMartinez** [comment]
![example](https://user-images.githubusercontent.com/88303169/179621324-ef88e73e-af9e-48f8-b462-7a1c06b706ee.png)

Image showing the problem

**Comment by groovemen** [comment]
Hello @ShoghiMartinez,

Thank you for using our products and for letting us know about this issue. Until the next product update I'll ask you to make the following change:
- please change the z-index of the `.swal2-container` from `z-index: 1060;` into `z-index: 10000;`
Hope this information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
